# Generated by Django 5.0.3 on 2024-03-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('connection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=50)),
                ('connection_string', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=100)),
            ],
        ),
    ]
